language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4.1
  - 2.5.1
  - jruby
  - rbx-2

gemfile:
  - gemfiles/ruby20.gemfile
  - gemfiles/sidekiq4.gemfile
  - gemfiles/upgrade.gemfile

script: "bundle exec rspec spec"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
