language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - jruby
  - rbx-2

gemfile:
  - gemfiles/sidekiq52_rails52.gemfile
  - gemfiles/sidekiq60_rails52.gemfile

script: "bundle exec rspec spec"

before_install:
  - gem install bundler

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx-2
